[package]
name = "solitaire"
version = "0.1.0"
authors = ["Mitchell Bruckner <mbruckner807@gmail.com>"]

[dependencies]
rand = "0.3"
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "release-0.4" }
cgmath = "*"

